"""empty message

Revision ID: 0d679bc021c9
Revises: 78d77155cf8c
Create Date: 2022-08-14 11:11:31.806932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d679bc021c9'
down_revision = '78d77155cf8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('genres', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('genres_venue_id_fkey', 'genres', type_='foreignkey')
    op.drop_column('genres', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('genres_venue_id_fkey', 'genres', 'venues', ['venue_id'], ['id'])
    op.alter_column('genres', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
