"""empty message

Revision ID: 24cfbfe8646c
Revises: 387ab0c77096
Create Date: 2022-08-14 10:42:53.800196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24cfbfe8646c'
down_revision = '387ab0c77096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('artists', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('locations', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('locations', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('shows', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('venues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('venues', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('venues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shows', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('locations', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('locations', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('artists', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('artists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
