"""empty message

Revision ID: 387ab0c77096
Revises: 5598d640a390
Create Date: 2022-08-13 00:08:13.226092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387ab0c77096'
down_revision = '5598d640a390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'artists', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_column('artists', 'location_id')
    # ### end Alembic commands ###
