"""empty message

Revision ID: 42058533a630
Revises: f8221c5b4a86
Create Date: 2022-08-14 11:49:39.463109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42058533a630'
down_revision = 'f8221c5b4a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_venue',
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre_venue')
    # ### end Alembic commands ###
