"""empty message

Revision ID: 4dd41dc425d0
Revises: faafe0bc16f4
Create Date: 2022-08-14 11:01:14.291659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd41dc425d0'
down_revision = 'faafe0bc16f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.add_column('genres', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'genres', 'artists', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'genres', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genres', type_='foreignkey')
    op.drop_constraint(None, 'genres', type_='foreignkey')
    op.drop_column('genres', 'artist_id')
    op.drop_column('genres', 'venue_id')
    # ### end Alembic commands ###
