"""empty message

Revision ID: c7835c2b3f9a
Revises: db90541bb26b
Create Date: 2022-08-12 23:44:15.218782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7835c2b3f9a'
down_revision = 'db90541bb26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'artists', 'locations', ['location_id'], ['id'])
    op.drop_column('artists', 'city')
    op.drop_column('artists', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_column('artists', 'location_id')
    # ### end Alembic commands ###
