"""empty message

Revision ID: d6fe37017424
Revises: 0d679bc021c9
Create Date: 2022-08-14 11:25:38.621472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fe37017424'
down_revision = '0d679bc021c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('genres_artist_id_fkey', 'genres', type_='foreignkey')
    op.drop_column('genres', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('genres_artist_id_fkey', 'genres', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###
