"""empty message

Revision ID: db90541bb26b
Revises: 51600360b41e
Create Date: 2022-08-12 21:37:36.157156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db90541bb26b'
down_revision = '51600360b41e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venues', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venues', 'locations', ['location_id'], ['id'])
    op.drop_column('venues', 'state')
    op.drop_column('venues', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'location_id')
    op.drop_table('locations')
    # ### end Alembic commands ###
