"""empty message

Revision ID: f8221c5b4a86
Revises: d6fe37017424
Create Date: 2022-08-14 11:34:05.247439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8221c5b4a86'
down_revision = 'd6fe37017424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_artist',
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('artis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artis_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre_artist')
    # ### end Alembic commands ###
